import os
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel
from dotenv import load_dotenv

from langgraph.graph import StateGraph, MessagesState, START, END
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.checkpoint.memory import MemorySaver
from langchain.chat_models import init_chat_model

# Load environment variables
load_dotenv()

app = FastAPI(title="LangGraph ChatGPT-like UI")

# Setup templates directory
templates = Jinja2Templates(directory="templates")

# Initialize LLM
llm = init_chat_model("google_genai:gemini-2.5-flash")

# Define LangGraph components
class State(MessagesState):
    pass

def chatbot_node(state: State):
    system_prompt = SystemMessage(content="You must answer every question with exactly one word.")
    messages = [system_prompt] + state["messages"]
    response = llm.invoke(messages)
    return {"messages": [response]}

# Build Graph
graph_builder = StateGraph(State)
graph_builder.add_node("chatbot", chatbot_node)
graph_builder.add_edge(START, "chatbot")
graph_builder.add_edge("chatbot", END)

memory = MemorySaver()
graph = graph_builder.compile(checkpointer=memory)

# Pydantic schema for requests
class ChatRequest(BaseModel):
    message: str
    thread_id: str = "default-user"

@app.get("/", response_class=HTMLResponse)
async def get_ui(request: Request):
    """Serves the primary ChatGPT-style chat page."""
    # Modern FastAPI syntax:
    return templates.TemplateResponse(request=request, name="index.html")

@app.post("/api/chat")
async def chat_endpoint(payload: ChatRequest):
    """Receives user input, runs LangGraph tracking state, and returns response."""
    if not payload.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")
        
    config = {"configurable": {"thread_id": payload.thread_id}}
    
    try:
        # Invoke the LangGraph compiled workflow
        result = graph.invoke(
            {"messages": [HumanMessage(content=payload.message)]}, 
            config=config
        )
        # Pull the last response generated by the system
        bot_reply = result["messages"][-1].content
        return {"status": "success", "reply": bot_reply}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
